version: '3'

services: 
  # postgres:
  #   image: 'postgres:latest'
  #   environment:
  #     - POSTGRES_PASSWORD=postgres_password

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment: 
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    volumes: 
      - ./backend:/usr/local/src/webapp
    # depends_on: 
    #   - postgres

  # nginx:
  #   restart: always
  #   build: 
  #     context: ./nginx
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - '3050:80'
  #   depends_on: 
  #     - api
